### ISSUE TITLE
Add Spanish translations to client

### ISSUE THREAD

**Issue by cainwatson** [JustDrawIt/drawit#221]
Add translations to https://github.com/JustDrawIt/drawit/blob/main/locales/es/translation.json

See https://github.com/JustDrawIt/drawit/blob/main/locales/en/translation.json for example of English translations. 

Keys will stay the same, but values are to be translated.

**Comment by cainwatson** [comment]
@natastro Would you like to take this?

**Comment by natastro** [comment]
Absolutely! Thank you @cainwatson 😄
